import {
    MessageSquare,
    BarChart3,
    Target,
    Clock,
    DollarSign,
    Users,
    Zap,
    TrendingDown,
    Calendar,
    BookOpen,
    ShoppingCart,
    Settings,
} from "lucide-react"


export const availableMetrics = {
    kpis: [
        {
            id: "conversaciones",
            name: "Conversaciones Totales",
            icon: MessageSquare,
            value: "316",
            trend: "+12%",
            color: "text-blue-600",
        },
        { id: "leads", name: "Leads Calificados", icon: Target, value: "127", trend: "+18%", color: "text-green-600" },
        {
            id: "conversion",
            name: "Tasa de Conversión",
            icon: BarChart3,
            value: "68%",
            trend: "+5%",
            color: "text-purple-600",
        },
        {
            id: "response_time",
            name: "Tiempo Respuesta",
            icon: Clock,
            value: "1.2s",
            trend: "-0.3s",
            color: "text-orange-600",
        },
        { id: "roi", name: "ROI", icon: DollarSign, value: "340%", trend: "+25%", color: "text-emerald-600" },
        {
            id: "cost_per_lead",
            name: "Costo por Lead",
            icon: TrendingDown,
            value: "$12",
            trend: "-15%",
            color: "text-red-600",
        },
        { id: "active_users", name: "Usuarios Activos", icon: Users, value: "89", trend: "+8%", color: "text-indigo-600" },
        {
            id: "automation_rate",
            name: "Tasa Automatización",
            icon: Zap,
            value: "94%",
            trend: "+3%",
            color: "text-yellow-600",
        },
    ],
    charts: [
        {
            id: "daily_conversations",
            name: "Conversaciones Diarias",
            description: "Evolución diaria de tu actividad comercial",
        },
        {
            id: "channel_performance",
            name: "Rendimiento por Canal",
            description: "Comparativa de efectividad entre canales",
        },
        { id: "sales_funnel", name: "Embudo de Ventas", description: "Progreso de leads a través del proceso" },
        { id: "response_times", name: "Tiempos de Respuesta", description: "Análisis de velocidad de respuesta" },
    ],
    widgets: [
        { id: "channel_status", name: "Estado de Canales", description: "Conecta y gestiona tus canales de comunicación" },
        { id: "quick_actions", name: "Acciones Rápidas", description: "Atajos para tareas comunes" },
        { id: "recent_activity", name: "Actividad Reciente", description: "Últimas acciones en tu plataforma" },
        { id: "ai_insights", name: "Insights Inteligentes", description: "Recomendaciones basadas en IA" },
        { id: "top_performers", name: "Top Performers", description: "Mejores asistentes y canales" },
        { id: "upcoming_tasks", name: "Tareas Pendientes", description: "Recordatorios y seguimientos" },
    ],
}

export
    // Tipos de agentes disponibles
    const TIPOS_AGENTES = [
        {
            id: "faq",
            nombre: "Agente de Preguntas Frecuentes",
            descripcion: "Responde automáticamente a preguntas comunes de tus clientes",
            icono: BookOpen,
            color: "bg-blue-500",
            pasos: ["Base de Conocimiento", "Canales", "Configuración"],
            casos: ["Soporte técnico", "Información de productos", "Políticas y procedimientos"],
        },
        {
            id: "leads",
            nombre: "Agente de Calificación de Leads",
            descripcion: "Califica automáticamente a tus prospectos según criterios BANT",
            icono: Target,
            color: "bg-green-500",
            pasos: ["Criterios de Calificación", "Preguntas", "Scoring", "Transferencia"],
            casos: ["Generación de leads", "Calificación inicial", "Filtrado de prospectos"],
        },
        {
            id: "agenda",
            nombre: "Agente de Agenda",
            descripcion: "Programa citas y demos sin intervención humana",
            icono: Calendar,
            color: "bg-purple-500",
            pasos: ["Calendario", "Disponibilidad", "Confirmaciones", "Recordatorios"],
            casos: ["Programación de demos", "Consultas", "Eventos"],
        },
        {
            id: "ventas",
            nombre: "Agente de Ventas Completo",
            descripcion: "Automatiza todo el proceso de ventas consultivas",
            icono: MessageSquare,
            color: "bg-orange-500",
            pasos: ["Negocio", "Proceso de Ventas", "Conocimiento", "Canales", "Escalamiento", "Activación"],
            casos: ["Ventas consultivas", "Ciclos largos", "Productos complejos"],
        },
        {
            id: "ecommerce",
            nombre: "Agente de eCommerce",
            descripcion: "Ayuda a tus clientes a encontrar y comprar productos",
            icono: ShoppingCart,
            color: "bg-pink-500",
            pasos: ["Catálogo", "Recomendaciones", "Checkout", "Post-venta"],
            casos: ["Tiendas online", "Marketplaces", "Venta de productos"],
        },
        {
            id: "personalizado",
            nombre: "Agente Personalizado",
            descripcion: "Configura un agente a medida para tu caso específico",
            icono: Settings,
            color: "bg-gray-500",
            pasos: ["Configuración libre", "Todos los módulos disponibles"],
            casos: ["Casos específicos", "Necesidades únicas", "Flujos complejos"],
        },
    ]

export const canalesData = [
    {
        id: "whatsappBusiness",
        nombre: "WhatsApp Business",
        descripcion: "Conecta tu WhatsApp Business mediante código QR",
        logo: "/images/whatsapp-business-logo.png",
        color: "green",
        conectado: true,
        tipo: "QR",
        limitaciones: ["Requiere WhatsApp Business", "Menos estable", "Conexión manual"],
        ventajas: ["Configuración rápida", "Sin verificación", "Gratis"],
        configuracion: "qr",
    },
    {
        id: "whatsappApi",
        nombre: "WhatsApp API Oficial",
        descripcion: "API oficial de Meta para empresas verificadas",
        logo: "/images/whatsapp-logo.png",
        color: "green",
        conectado: false,
        tipo: "API",
        limitaciones: ["Requiere verificación de Meta", "Proceso de aprobación"],
        ventajas: ["Más estable", "Oficial", "Webhooks", "Sin límites"],
        configuracion: "api",
    },
    {
        id: "instagram",
        nombre: "Instagram",
        descripcion: "Mensajes directos de Instagram Business",
        logo: "/images/instagram-logo.png",
        color: "pink",
        conectado: false,
        tipo: "API",
        limitaciones: ["Requiere cuenta Business", "Conectar con Facebook"],
        ventajas: ["Audiencia joven", "Visual", "Stories"],
        configuracion: "oauth",
    },
    {
        id: "messenger",
        nombre: "Facebook Messenger",
        descripcion: "Chat de Facebook para páginas empresariales",
        logo: "/images/messenger-logo.png",
        color: "blue",
        conectado: true,
        tipo: "API",
        limitaciones: ["Requiere página de Facebook", "Revisión de Meta"],
        ventajas: ["Gran alcance", "Integración Facebook", "Bots avanzados"],
        configuracion: "oauth",
    },
]

export const stats = {
    canalesActivos: 1,
    mensajesHoy: 1247,
    conversacionesActivas: 89,
    tiempoRespuesta: "2.3min",
}


export const usuarios = [
    {
        id: "1",
        nombre: "Juan",
        apellido: "Pérez",
        email: "juan.perez@empresa.com",
        rol: "administrador",
        estado: "activo",
        ultimoAcceso: "Hace 2 horas",
    },
    {
        id: "2",
        nombre: "María",
        apellido: "García",
        email: "maria.garcia@empresa.com",
        rol: "supervisor",
        estado: "activo",
        ultimoAcceso: "Hace 1 hora",
    },
]

// Datos mock para simular la integración con Airtable

export const mockAsistentes = [
  {
    id: "1",
    nombre: "Asistente Inmobiliario",
    canal: "WhatsApp",
    personalidad: "formal",
    promptBase:
      "Eres un especialista en bienes raíces. Tu objetivo es calificar leads interesados en propiedades, obtener información sobre su presupuesto, ubicación preferida y necesidades específicas. Mantén un tono profesional y ayuda a los clientes a encontrar la propiedad ideal.",
    fechaCreacion: "15 Nov 2024",
    conversacionesTotales: 45,
    estado: "activo",
  },
  {
    id: "2",
    nombre: "Bot Automotriz",
    canal: "Instagram",
    personalidad: "casual",
    promptBase:
      "Eres un experto en vehículos que ayuda a los clientes a encontrar el auto perfecto. Pregunta sobre sus necesidades, presupuesto y preferencias. Usa un tono amigable y entusiasta para crear una experiencia positiva.",
    fechaCreacion: "12 Nov 2024",
    conversacionesTotales: 32,
    estado: "activo",
  },
  {
    id: "3",
    nombre: "Consultor Seguros",
    canal: "Facebook",
    personalidad: "técnico",
    promptBase:
      "Eres un asesor especializado en seguros. Tu misión es entender las necesidades de protección del cliente y recomendar las mejores opciones. Explica los beneficios de manera clara y técnica, pero accesible.",
    fechaCreacion: "10 Nov 2024",
    conversacionesTotales: 28,
    estado: "activo",
  },
]

export const mockConversaciones = [
  {
    id: "1",
    nombreLead: "María González",
    ultimoMensaje: "Estoy interesada en un departamento de 2 ambientes en Palermo",
    estado: "nuevo",
    canal: "WhatsApp",
    fechaUltimoMensaje: "16 Nov 2024, 14:30",
    totalMensajes: 5,
    asistenteId: "1",
    vendedorAsignado: "Juan Pérez",
  },
  {
    id: "2",
    nombreLead: "Carlos Ruiz",
    ultimoMensaje: "Mi presupuesto es de $25,000 USD para un auto usado",
    estado: "calificado",
    canal: "Instagram",
    fechaUltimoMensaje: "16 Nov 2024, 13:45",
    totalMensajes: 12,
    asistenteId: "2",
    vendedorAsignado: "María García",
  },
  {
    id: "3",
    nombreLead: "Ana Martínez",
    ultimoMensaje: "Necesito un seguro de vida para mi familia",
    estado: "agendado",
    canal: "Facebook",
    fechaUltimoMensaje: "16 Nov 2024, 12:20",
    totalMensajes: 8,
    asistenteId: "3",
    vendedorAsignado: "Carlos López",
  },
  {
    id: "4",
    nombreLead: "Roberto Silva",
    ultimoMensaje: "Solo estaba consultando precios, gracias",
    estado: "descartado",
    canal: "WhatsApp",
    fechaUltimoMensaje: "16 Nov 2024, 11:15",
    totalMensajes: 3,
    asistenteId: "1",
    vendedorAsignado: null,
  },
  {
    id: "5",
    nombreLead: "Laura Fernández",
    ultimoMensaje: "¿Tienen financiación para autos nuevos?",
    estado: "nuevo",
    canal: "Instagram",
    fechaUltimoMensaje: "16 Nov 2024, 10:30",
    totalMensajes: 7,
    asistenteId: "2",
    vendedorAsignado: null,
  },
  {
    id: "6",
    nombreLead: "Diego Morales",
    ultimoMensaje: "Perfecto, espero la llamada del agente",
    estado: "calificado",
    canal: "WhatsApp",
    fechaUltimoMensaje: "16 Nov 2024, 09:45",
    totalMensajes: 15,
    asistenteId: "1",
    vendedorAsignado: "Ana Martínez",
  },
]

export const mockContactos = [
  {
    id: "1",
    nombre: "María",
    apellido: "González",
    email: "maria.gonzalez@email.com",
    telefono: "+54 9 11 1234-5678",
    canal: "WhatsApp",
    fechaCreacion: "15 Nov 2024",
    origen: "Publicidad Facebook",
    etiquetas: ["Inmobiliario", "Palermo", "2 ambientes"],
    estado: "nuevo",
    empresa: "Consultora ABC",
  },
  {
    id: "2",
    nombre: "Carlos",
    apellido: "Ruiz",
    email: "carlos.ruiz@email.com",
    telefono: "+54 9 11 2345-6789",
    canal: "Instagram",
    fechaCreacion: "14 Nov 2024",
    origen: "Instagram Ads",
    etiquetas: ["Automotriz", "Usado", "$25k"],
    estado: "calificado",
    empresa: "Empresa XYZ",
  },
  {
    id: "3",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@email.com",
    telefono: "+54 9 11 3456-7890",
    canal: "Facebook",
    fechaCreacion: "13 Nov 2024",
    origen: "Referido",
    etiquetas: ["Seguros", "Vida", "Familia"],
    estado: "agendado",
    empresa: "Startup DEF",
  },
  {
    id: "4",
    nombre: "Roberto",
    apellido: "Silva",
    email: "roberto.silva@email.com",
    telefono: "+54 9 11 4567-8901",
    canal: "WhatsApp",
    fechaCreacion: "12 Nov 2024",
    origen: "Google Ads",
    etiquetas: ["Inmobiliario", "Consulta"],
    estado: "descartado",
    empresa: null,
  },
  {
    id: "5",
    nombre: "Laura",
    apellido: "Fernández",
    email: "laura.fernandez@email.com",
    telefono: "+54 9 11 5678-9012",
    canal: "Instagram",
    fechaCreacion: "11 Nov 2024",
    origen: "Instagram Orgánico",
    etiquetas: ["Automotriz", "Financiación", "Nuevo"],
    estado: "nuevo",
    empresa: "Corporación GHI",
  },
  {
    id: "6",
    nombre: "Diego",
    apellido: "Morales",
    email: "diego.morales@email.com",
    telefono: "+54 9 11 6789-0123",
    canal: "WhatsApp",
    fechaCreacion: "10 Nov 2024",
    origen: "Referido",
    etiquetas: ["Inmobiliario", "Calificado", "Urgente"],
    estado: "calificado",
    empresa: "Empresa JKL",
  },
  {
    id: "7",
    nombre: "Sofía",
    apellido: "López",
    email: "sofia.lopez@email.com",
    telefono: "+54 9 11 7890-1234",
    canal: "Web",
    fechaCreacion: "09 Nov 2024",
    origen: "Formulario Web",
    etiquetas: ["Seguros", "Auto", "Cotización"],
    estado: "cliente",
    empresa: "Empresa MNO",
  },
]

export const mockMensajes = [
  {
    id: "1",
    tipo: "asistente" as const,
    contenido: "¡Hola! Soy el Asistente Inmobiliario de Aurelia. ¿En qué puedo ayudarte hoy?",
    timestamp: "14:25",
    fecha: "16 Nov 2024",
  },
  {
    id: "2",
    tipo: "usuario" as const,
    contenido: "Hola, estoy buscando un departamento para comprar",
    timestamp: "14:26",
    fecha: "16 Nov 2024",
  },
  {
    id: "3",
    tipo: "asistente" as const,
    contenido:
      "Perfecto, me encanta ayudarte con eso. Para encontrar las mejores opciones, ¿podrías contarme un poco más sobre lo que buscas? Por ejemplo: ¿cuántos ambientes necesitas?",
    timestamp: "14:26",
    fecha: "16 Nov 2024",
  },
  {
    id: "4",
    tipo: "usuario" as const,
    contenido: "Busco un 2 ambientes, preferiblemente en Palermo o Villa Crick",
    timestamp: "14:28",
    fecha: "16 Nov 2024",
  },
  {
    id: "5",
    tipo: "asistente" as const,
    contenido: "Excelente elección de zonas. ¿Cuál es tu presupuesto aproximado para esta compra?",
    timestamp: "14:29",
    fecha: "16 Nov 2024",
  },
  {
    id: "6",
    tipo: "usuario" as const,
    contenido: "Mi presupuesto está entre $180,000 y $220,000 USD",
    timestamp: "14:30",
    fecha: "16 Nov 2024",
  },
]

// Datos para CRM
export const mockCrmData = {
  columnas: [
    { id: "prospecto", nombre: "Prospecto", color: "#3B82F6" },
    { id: "calificado", nombre: "Calificado", color: "#10B981" },
    { id: "propuesta", nombre: "Propuesta", color: "#F59E0B" },
    { id: "cerrado", nombre: "Cerrado", color: "#8B5CF6" },
  ],
  oportunidades: [
    {
      id: "1",
      contacto: "María González",
      empresa: "Consultora ABC",
      valor: 180000,
      estado: "prospecto",
      vendedor: "Juan Pérez",
      fechaCierre: "30 Nov 2024",
      probabilidad: 25,
    },
    {
      id: "2",
      contacto: "Carlos Ruiz",
      empresa: "Empresa XYZ",
      valor: 25000,
      estado: "calificado",
      vendedor: "María García",
      fechaCierre: "25 Nov 2024",
      probabilidad: 60,
    },
    {
      id: "3",
      contacto: "Ana Martínez",
      empresa: "Startup DEF",
      valor: 15000,
      estado: "propuesta",
      vendedor: "Carlos López",
      fechaCierre: "20 Nov 2024",
      probabilidad: 80,
    },
    {
      id: "4",
      contacto: "Diego Morales",
      empresa: "Empresa JKL",
      valor: 220000,
      estado: "cerrado",
      vendedor: "Ana Martínez",
      fechaCierre: "18 Nov 2024",
      probabilidad: 100,
    },
    {
      id: "5",
      contacto: "Laura Fernández",
      empresa: "Corporación GHI",
      valor: 35000,
      estado: "prospecto",
      vendedor: "Juan Pérez",
      fechaCierre: "05 Dic 2024",
      probabilidad: 20,
    },
    {
      id: "6",
      contacto: "Sofía López",
      empresa: "Empresa MNO",
      valor: 8000,
      estado: "calificado",
      vendedor: "María García",
      fechaCierre: "28 Nov 2024",
      probabilidad: 70,
    },
  ],
}

// Datos para métricas
export const mockMetricas = {
  mensajesPorDia: [
    { dia: "Lun", mensajes: 45, asistente: 32, usuario: 13 },
    { dia: "Mar", mensajes: 52, asistente: 38, usuario: 14 },
    { dia: "Mié", mensajes: 38, asistente: 28, usuario: 10 },
    { dia: "Jue", mensajes: 61, asistente: 44, usuario: 17 },
    { dia: "Vie", mensajes: 73, asistente: 51, usuario: 22 },
    { dia: "Sáb", mensajes: 29, asistente: 21, usuario: 8 },
    { dia: "Dom", mensajes: 18, asistente: 13, usuario: 5 },
  ],
  leadsCalificacion: [
    { name: "Calificados", value: 68, color: "#10B981" },
    { name: "Descartados", value: 32, color: "#EF4444" },
  ],
  estadosContactos: [
    { name: "Nuevos", value: 35, color: "#3B82F6" },
    { name: "Calificados", value: 25, color: "#10B981" },
    { name: "Agendados", value: 15, color: "#8B5CF6" },
    { name: "Clientes", value: 20, color: "#F59E0B" },
    { name: "Descartados", value: 5, color: "#EF4444" },
  ],
  conversionPorCanal: [
    { canal: "WhatsApp", leads: 45, calificados: 32, tasa: 71 },
    { canal: "Instagram", leads: 28, calificados: 18, tasa: 64 },
    { canal: "Facebook", leads: 19, calificados: 11, tasa: 58 },
  ],
}

// Datos para usuarios
export const mockUsuarios = [
  {
    id: "1",
    nombre: "Juan",
    apellido: "Pérez",
    email: "juan.perez@empresa.com",
    telefono: "+54 9 11 1234-5678",
    rol: "administrador",
    equipo: "Ventas",
    estado: "activo",
    ultimoAcceso: "Hace 2 horas",
    fechaCreacion: "15 Oct 2024",
    oportunidadesAsignadas: 12,
  },
  // ... más usuarios
]

// Constantes para los pasos
export const PASOS_LEADS = [
  { id: 1, nombre: "Información Básica", icono: <Briefcase className="w-4 h-4" /> },
  { id: 2, nombre: "Criterios de Calificación", icono: <ClipboardCheck className="w-4 h-4" /> },
  { id: 3, nombre: "Preguntas de Descubrimiento", icono: <MessageSquare className="w-4 h-4" /> },
  { id: 4, nombre: "Configuración de Scoring", icono: <Target className="w-4 h-4" /> },
  { id: 5, nombre: "Canales", icono: <GitBranch className="w-4 h-4" /> },
  { id: 6, nombre: "Escalamiento", icono: <Brain className="w-4 h-4" /> },
  { id: 7, nombre: "Automatizaciones", icono: <Zap className="w-4 h-4" /> },
  { id: 8, nombre: "Playground", icono: <PlayCircle className="w-4 h-4" /> },
]